[pytest]
asyncio_mode = auto
filterwarnings =
    ignore:pkg_resources is deprecated as an API:UserWarning:apscheduler
    ignore:Deprecated call to `pkg_resources.declare_namespace\('sphinxcontrib'\)`:DeprecationWarning:pkg_resources
    ignore:Deprecated call to `pkg_resources.declare_namespace\('zc'\)`:DeprecationWarning:pkg_resources
